server:
  port: 8081
spring:
  jmx:
    enabled: false
  datasource:
     url: jdbc:mysql://localhost:3306/scape?useUnicode=true&characterEncoding=utf8
     username: root
     password: 123456
     # password: ee32854224da154d
     driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      # 页面默认前缀目录
      prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.lhl.hotelmanager.entity  # 注意：对应实体类的路径
logging:
#   config: classpath:log4j_dev.xml
#    path: classpath:logs
#    file: mylog.log